# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ravendel Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/RavendelR/RavenLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/RavendelR/RavenLauncher"
supportLink = "https://github.com/RavendelR/RavenLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue dans Ravendel !"
welcomeDescription = "Amusez vous bien !"
welcomeDescCTA = "Bientôt arrivé à Bergheim..."
